FROM python:3.11-slim

WORKDIR /tmp

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    pandas \
    scikit-learn \
    numpy \
    opencv-python-headless \
    torch \
    torchvision \
    pillow

# Run non-root user
RUN useradd -m sandboxuser
USER sandboxuser
