"""initial_schema

Revision ID: a833c270e807
Revises: 
Create Date: 2026-07-26 23:37:38.598059+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a833c270e807'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('PUBLIC', 'COMPETITION', name='challenge_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='challenge_status_enum'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_lock_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_direction', sa.Enum('HIGHER_IS_BETTER', 'LOWER_IS_BETTER', name='metric_direction_enum'), nullable=False),
    sa.Column('custom_metric_url', sa.String(length=1000), nullable=True),
    sa.Column('dataset_url', sa.String(length=1000), nullable=False),
    sa.Column('ground_truth_url', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'user_id', name='uq_participant_challenge_user')
    )
    op.create_index(op.f('ix_challenge_participants_challenge_id'), 'challenge_participants', ['challenge_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_challenge_id'), 'teams', ['challenge_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_md5_hash', sa.String(length=32), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('source_code_url', sa.String(length=1000), nullable=True),
    sa.Column('public_score', sa.Double(), nullable=True),
    sa.Column('private_score', sa.Double(), nullable=True),
    sa.Column('is_selected_for_private', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='submission_status_enum'), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'team_id', 'file_md5_hash', name='uq_submission_md5')
    )
    op.create_index(op.f('ix_submissions_challenge_id'), 'submissions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_submissions_team_id'), 'submissions', ['team_id'], unique=False)
    op.create_table('team_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=False),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='invite_status_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_team_invites_team_id'), 'team_invites', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('leaderboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('best_public_score', sa.Double(), nullable=False),
    sa.Column('best_private_score', sa.Double(), nullable=True),
    sa.Column('best_public_submission_id', sa.UUID(), nullable=True),
    sa.Column('best_private_submission_id', sa.UUID(), nullable=True),
    sa.Column('last_submission_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['best_private_submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['best_public_submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'team_id', name='uq_leaderboard_challenge_team')
    )
    op.create_index(op.f('ix_leaderboard_challenge_id'), 'leaderboard', ['challenge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_challenge_id'), table_name='leaderboard')
    op.drop_table('leaderboard')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_team_invites_team_id'), table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_index(op.f('ix_submissions_team_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_challenge_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_teams_challenge_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_challenge_participants_challenge_id'), table_name='challenge_participants')
    op.drop_table('challenge_participants')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # Bổ sung xóa các custom ENUM types trong Postgres khi downgrade
    op.execute("DROP TYPE IF EXISTS user_role_enum")
    op.execute("DROP TYPE IF EXISTS challenge_type_enum")
    op.execute("DROP TYPE IF EXISTS challenge_status_enum")
    op.execute("DROP TYPE IF EXISTS metric_direction_enum")
    op.execute("DROP TYPE IF EXISTS submission_status_enum")
    op.execute("DROP TYPE IF EXISTS invite_status_enum")
    # ### end Alembic commands ###
