"""Add updated_at to challenges and fix password_resets indexes

Revision ID: 6a2c3f9b1d8e
Revises: e58789d78e68
Create Date: 2026-08-14 01:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2c3f9b1d8e'
down_revision: Union[str, None] = 'e58789d78e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # We drop the unique constraint from tokens if it existed
    try:
        op.drop_constraint('password_resets_token_key', 'password_resets', type_='unique')
    except Exception:
        pass
    
    try:
        op.drop_index('ix_password_resets_user_id_expires_at', table_name='password_resets')
    except Exception:
        pass
    
    try:
        op.drop_index('ix_password_resets_token', table_name='password_resets')
    except Exception:
        pass
        
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.create_index('ix_password_resets_token', 'password_resets', ['token'], unique=False)
    
    try:
        op.create_unique_constraint('password_resets_token_key', 'password_resets', ['token'])
    except Exception:
        pass
        
    op.create_index('ix_password_resets_user_id_expires_at', 'password_resets', ['user_id', 'expires_at'], unique=False)
    op.drop_column('challenges', 'updated_at')
    # ### end Alembic commands ###
