"""add submission compound index

Revision ID: 88f673c4a16a
Revises: 159a4545b89b
Create Date: 2026-07-28 00:45:49.853406+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f673c4a16a'
down_revision: Union[str, None] = '159a4545b89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_submission_team_challenge', 'submissions', ['team_id', 'challenge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_submission_team_challenge', table_name='submissions')
    # ### end Alembic commands ###
