"""Add contests table

Revision ID: b89136e1d320
Revises: 354e9afefb67
Create Date: 2026-07-31 22:25:23.031784+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89136e1d320'
down_revision: Union[str, None] = '354e9afefb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='contest_status_enum'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('challenges', sa.Column('contest_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'challenges', 'contests', ['contest_id'], ['id'])
    op.drop_index(op.f('ix_solution_upvotes_solution_id'), table_name='solution_upvotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_solution_upvotes_solution_id'), 'solution_upvotes', ['solution_id'], unique=False)
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_column('challenges', 'contest_id')
    op.drop_table('contests')
    # ### end Alembic commands ###
