"""Add Solution table

Revision ID: 112fa9d5e069
Revises: a833c270e807
Create Date: 2026-07-27 11:27:11.580845+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112fa9d5e069'
down_revision: Union[str, None] = 'a833c270e807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('notebook_url', sa.String(length=1000), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_challenge_id'), 'solutions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_solutions_user_id'), 'solutions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solutions_user_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_challenge_id'), table_name='solutions')
    op.drop_table('solutions')
    # ### end Alembic commands ###
