"""add dynamic sandbox config with default

Revision ID: f2fbe3d4c86d
Revises: c3d4e5f6a7b8
Create Date: 2026-08-03 21:42:48.954381+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fbe3d4c86d'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('environment_image', sa.String(length=255), server_default='ictu-ai-judge-sandbox:latest', nullable=False))
    op.add_column('challenges', sa.Column('require_gpu', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_challenges_contest_id'), table_name='challenges')
    op.drop_index(op.f('ix_contests_active'), table_name='contests', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_solution_upvotes_solution_id'), table_name='solution_upvotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_solution_upvotes_solution_id'), 'solution_upvotes', ['solution_id'], unique=False)
    op.create_index(op.f('ix_contests_active'), 'contests', [sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_challenges_contest_id'), 'challenges', ['contest_id'], unique=False)
    op.drop_column('challenges', 'require_gpu')
    op.drop_column('challenges', 'environment_image')
    # ### end Alembic commands ###
